
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    build:
      context: .
      dockerfile: ${BUILD_TYPE}/Dockerfile
    volumes:
      - ./public_html:/var/www/html
    networks:
      - mynetwork

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork: